FROM node:22-alpine

WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json tsconfig.json .eslintrc.json nest-cli.json ./
COPY packages ./packages
COPY apps ./apps
COPY prisma ./prisma

RUN corepack enable && corepack prepare pnpm@11.18.0 --activate
RUN pnpm install --frozen-lockfile
RUN pnpm run prisma:generate
RUN pnpm --filter api-gateway... run build

EXPOSE 3000

CMD ["node", "apps/api-gateway/dist/main.js"]
